services:
  - type: web
    name: data-science-chatbot
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt && python migrate_db.py
    startCommand: gunicorn app:app --workers 2 --timeout 120 --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: POETRY_ACTIVE
        value: 0
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false

databases:
  - name: chatbot-db
    databaseName: chatbot
    plan: free